from . import opd_ticket
from . import department
from . import diagnosisgroup
from . import sample_type
from . import examinationentry
from . import examine_package
from . import blood
from . import products_lens
from . import patient_info
from . import optics_sale
from . import advance_cash
from . import bill_register